# Site
name: "Blog | Ruby Phan"
title: "Ruby Phan"
description: "I will take you on the fabulous world of exploration. Eat, Pray, Love!"
logo: 'assets/images/logo-1.png'
favicon: 'assets/images/logo-1.png'
baseurl: ''
google_analytics: 
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Multilanguage
lang: en

# Authors
authors:
  ruby:
    name: Ruby Phan
    display_name: Ruby Phan
    avatar: 'assets/images/avatar-ruby-300.png'
    email: ruby@rubyphan.com
    web: https://rubyphan.com
    description: "Hello, I'm a free spirit who like to explore the world"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tags
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

#Comment
comment_issue_id: 1

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
